image: archlinux
packages:
  - go 
sources:
  - https://git.sr.ht/~psic4t/qcal
environment:
deploy: psic4t@data.haus
secrets:
  - 46f739e5-4538-45dd-a79f-bf173b7a2ed9
tasks:
  - build: |
    cd qcal
    make
